45장 프로미스

# 프로미스

자바스크립트는 비동기 처리를 위해서 콜백함수를 사용하는데 콜백함수는 콜백지옥 (Callback Hell)이라는 문제가 있다.

## 콜백헬

> 콜백지옥이란?
>
> 1. 중첩된 콜백: 비동기 작업이 완료된 후 비동기 작업을 수행하기 위해 콜백함수를 중첩해서 아용하면 코드가 깊게 중첩되서 가독성이 떨어진다. 그래서 유지보수도 어려움
> 2. 에러 처리의 복잡성: 콜백 함수 내부에서 발생한 에러를 외부에서 캐치하기 어렵다.

🔥콜백지옥의 예시🔥

```js
get(`/step1`, (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${b}`, (c) => {
      get(`/step4/${c}`, (d) => {
        console.log(d);
      });
    });
  });
});
```

- 각 단계가 다음 단계에 의존하고 있기 때문에 코드 흐름을 이해하기 어려움
- 각 콜백의 역할을 파악하기 힘들어짐
- 각 콜백에서 발생할 수 있는 에러 처리를 각 단계마다 해줘야해서 에러 발생 시 원인을 파악하기 어려움

> ### try ... catch ... finally
>
> - 에러 처리를 위한 문법
>
> 1. try 에서 에러가 발생하면
> 2. catch 문의 err 변수에 전달되고 catch 문의 문장이 실행된다.
> 3. finally 문은 에러 발생 여부와 상관없이 반드시 실행된다.

이러한 문제를 해결하기 위해서 ✨`프로미스`✨가 등장했다.

## 프로미스 생성

Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.

```js
const Promise = new Promise((resolve, reject) = > {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
	if(/* 비동기 처리 성공 */){
    	resolve('result');
    }else{
  		/* 비동기 처리 실패 */
		reject('failure reason');
	}
})
```

🙆🏼‍♂️ 비동기 처리 성공시: resolve 함수를 호출하고 처리 결과를 인수로 전달

🙅🏼‍♂️ 비동기 처리 실패시: reject 함수를 호출하고 에러의 원인을 인수로 전달

#### 프로미스의 상태 정보

- `pending`: 비동기 처리가 아직 수행되지 않은 상태
- `fulfilled`: 비동기 처리가 수행된 상태 (resolve 함수 호출)
- `rejected`: 비동기 처리가 수행된 상태 (reject 함수 호출)

#### 프로미스의 상태 변경 조건

- `pending`: 프로미스가 생성된 직후 기본 상태
- `fulfilled`: resolve 함수가 호출된 경우
- `rejected`: reject 함수가 호출된 경우

생성된 직후의 프로미스는 기본적으로 pending 상태이며, 비동기 처리에 따라 fulfilled 또는 rejected 상태가 된다.

`settled`: fulfilled 또는 rejected 상태 (성공 여부와 상관없이 비동기가 처리된 최종 상태)

## 프로미스의 후속 처리 메서드

프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야 한다.

프로미스 후속 메서드: `then`, `catch`, `finally`

### then

2개의 콜백 함수를 인수로 전달받는다.

- 첫번째 콜백 함수: 프로미스가 fulfilled 상태가 되면 호출된다.
- 두번째 콜백 함수: 프로미스가 rejected 상태가 되면 호출된다.

```js
// 비동기 처리 성공
new Promise((resolve) => resolve("fulfilled")).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled

// 비동기 처리 실패
new Promise((resolve, reject) => reject("rejected")).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // rejected
```

- rejected 상태일 때 거부된 값을 처리하는 콜백함수를 받을 수도 있고 생략할 수도 있지만 자동적으로 다음 catch 메서드로 전파되어 처리된다.

- then 메서드는 언제나 프로미스를 반환하는데 이때 다음 then 메서드는 그 프로미스가 이행될 때까지 대기하게 되어서 작업을 순차적으로 처리할 수 있다. 이것을 `프로미스 체이닝`이라고 한다.

### catch

- 프로미스가 rejected 상태가 되면 호출된다.
- 1개의 콜백 함수를 인수로 전달받는다.
- 콜백 함수는 프로미스가 거부된 이유를 설명하는 에러를 인수로 전달받는다.

```js
new Promise((resolve) => reject(new Error("rejected"))).catch((e) =>
  console.log(e)
); // Error: rejected
```

### finally

- 1개의 콜백 함수를 인수로 전달받는다.
- 프로미스의 성공 여부와 상관없이 무조건 한 번 호출된다.
- 프로미스의 최종 상태와 상관없이 공통적으로 수행해야 할 처리 내용을 명시할 때 사용한다.

```js
new Promise(() => {}).finally(() => console.log("finally")); // finally
```

#### 후속 처리 구현

```js
const get = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest(); // XMLHttpRequest 객체 생성 (HTTP 요청 생성 및 관리)
    xhr.open("GET", url); // GET 요청을 위한 초기화
    xhr.send(); // 요청 전송

    xhr.onload = () => {
      // 요청이 완료되었을 때 호출되는 콜백
      if (xhr.status === 200) {
        // HTTP 응답 상태가 200 (성공)일 경우
        resolve(JSON.parse(xhr.response)); // 응답을 JSON으로 파싱하여 resolve 호출
      } else {
        reject(new Error(xhr.status)); // 에러 발생 시 reject 호출
      }
    };
  });
};

get("https://~~") // get 함수 호출
  .then((res) => console.log(res)) // 성공적으로 데이터를 가져오면 결과를 콘솔에 출력
  .catch((err) => console.error(err)) // 에러가 발생하면 에러 메시지를 콘솔에 출력
  .finally(() => console.log("Bye")); // 요청이 완료된 후 항상 실행됨
```

## 프로미스의 에러 처리

#### then의 두번째 매개변수

- 프로미스가 rejected 상태가 되면 호출된다.
- 콜백 함수는 프로미스가 거부된 이유를 설명하는 에러를 인수로 전달받는다.

```js
promise.then(
  (result) => {
    // 성공적으로 이행된 경우 처리
  },
  (error) => {
    // 거부된 경우 처리 (에러 처리)
  }
);
```

#### catch

- 프로미스가 rejected 상태가 되면 호출된다.
- 1개의 콜백 함수를 인수로 전달받는다.
- 콜백 함수는 프로미스가 거부된 이유를 설명하는 에러를 인수로 전달받는다.

```js
promise
  .then((result) => {
    // 성공적으로 이행된 경우 처리
    throw new Error("문제가 발생했습니다!"); // 에러 발생
  })
  .catch((error) => {
    // 에러 처리 (에러 전파)
    console.error("에러:", error);
  });
```

- then의 두번째 매개변수로 에러 처리하는건 만약에 여러 개의 then이 체인으로 연결된 경우 각 단계에서 에러를 처리해야하는데 중간에서 발생한 에러를 처리하려면 콜백 함수를 작성해야하는 모순 발생

- catch 메서드는 프로미스 체인에서 발생한 모든 에러를 한 곳에서 처리하기 때문에 편하긴한데 중간 단계에서 발생한 에러가 자동으로 다음 .catch()로 전파되서 어떤 에러가 발생했는 지 파악하기 어려울 수도 있음

**결론**: 그래도 then 보다 catch가 가독성도 좋고 에러 처리도 편하기 때문에 `.catch()` 메서드를 사용하는 것이 더 나음

## 45.5 프로미스 체이닝

then, catch, finally 후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있는데, 이를 프로미스 체이닝이라 한다.

프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백 헬이 발생하지 않는다. 다만 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다. 콜백 패턴은 가독성이 좋지 않은데 이 문제는 ES8에서 도입된 async/await를 통해 해결할 수 있다. async/await를 사용하면 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 구현할 수 있다.

## 45.6 프로미스의 정적 메서드

### 45.6.1 Promise.resolve / Promise.reject

이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

Promise.resolve 메서드는 인수로 전달받은 값을 resolve하는 프로미스를 생성한다.

Promise.reject 메서드는 인수로 전달받은 값을 reject하는 프로미스를 생성한다.

```javascript
// 배열을 resolve/reject 하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
const rejectedPromise = Promise.reject(new Error("Error"));

// 위와 동일함
const resolvedPromise = new Promise((resolve) => resolve([1, 2, 3]));
const rejectedPromise = new Promise((_, reject) => reject(new Error("Error")));
```

### 45.6.2 Promise.all

여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.

```javascript
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1, 2, 3]
  .catch(console.error);
```

### 45.6.3 Promise.race

Promise.all 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. Promise.all 처럼 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 것이 아니라 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 반환한다.

```javascript
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.race([requestData1(), requestData2(), requestData3()])
  .then(console.log) // 3
  .catch(console.error);
```

### 45.6.4 Promise.allSettled

전달받은 프로미스가 모두 settled 상태가 되면 처리 결과를 배열로 반환한다. Promise.allSettled 메서드가 반환한 배열에는 fulfilled 또는 rejected 상태와는 상관없이 Promise.allSettled 메서드가 인수로 전달받은 모든 프로미스들의 처리 결과가 모두 담겨 있다.

## 45.7 마이크로태스트 큐

```javascript
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

위 예제의 출력 순서는 2 -> 3 -> 1 이다. 그 이유는 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로태스크 큐에 저장되기 때문이다. 콜백 함수나 이벤트 핸들러를 일시 저장한다는 점에서 태스크 큐와 동일하지만 마이크로태스크 큐는 태스크 큐보다 우선순위가 높다.

즉, 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행한다. 이후 마이크로태스크 큐가 비면 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

## 45.8 fetch

fetch 함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다.

fetch 함수는 XMLHttpRequest 객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

fetch 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

```javascript
const promise = fetch(url, [, options]);
```

fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.

fetch 함수가 반환하는 프로미스는 기본적으로 404나 500 같은 HTTP 에러가 발생해도 에러를 reject하지 않고 Response 객체를 resolve한다. 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject한다. 따라서 fetch 함수를 사용할 때는 fetch 함수가 반환한 프로미스가 resolve한 불리언 타입의 ok 상태를 확인해 명시적으로 에러를 처리해야 한다.

참고로 axios는 모든 HTTP 에러를 reject하는 프로미스를 반환한다. 따라서 모든 에러를 catch에서 처리할 수 있어 편리하다. 또한, axios는 인터셉터, 요청 설정 등 더 다양한 기능을 제공한다.
