# 45장 프로미스

- 자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용, 하지만 전통적인 콜백 패턴은 콜백 헬로 인해 가독성이 나쁘고 비동기 처리 중 발생한 에러의 처리가 곤란하며 여러 개의 비동기 처리를 한번에 처리하는 데도 한계 존재.

- ES6에서는 비동기 처리를 위한 또 다른 패턴으로 프로미스를 도입, 전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점 소유.
<br>

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1 콜백 헬

- 먼저 44.3.4절 “GET 요청”에서 살펴본 바와 같이 GET 요청을 위한 함수를 작성.

```js
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();

  xhr.open('GET', url);

  xhr.send();

  xhr.onload =()=>{
    if (xhr.status === 200) {
      // 서버의 응답을 콘솔에 출력한다.
      console.log(JSON.parse(xhr.response));
    } else {
      console.error('${xhr.status} ${xhr.statusText}'); 
    }
  };
};

// id가 1 인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1');
/*
  {
    "userid": 1,
    "id": 1,
    "title": "sunt aut facere ... ",
    "body": "quia et suscipit ... " 
  }
*/
```

- get 함수가 서버의 응답 결과를 반환하게 하려면 어떻게 하면 될까?

  - get 함수는 비동기 함수로 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다해도 기다리지 않고 즉시 종료.
 
  - 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작 X.

- 비동기 함수인 get 함수 내부의 onload 이벤트 핸들러는 get 함수가 종료된 이후에 실행되기에 get 함수의 onload 이벤트 핸들러에서 서버의 응답 결과를 반환하거나 상위 스코프의 변수에 할당 시 기대한 대로 동작 X.

- get 함수가 서버의 응답 결과를 반환하도록 수정.

```js
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();

  xhr.open('GET', url);

  xhr.send();

  xhr.onload =()=>{
    if (xhr.status === 200) {
      // ① 서버의 응답을 반환한다.
      return JSON.parse(xhr.response);
    } 

    console.error( ${xhr.status} ${xhr.statusText}');
  };
};

// ② id가 1 인 post를 취득
const response = get('https://jsonplaceholder.typicode.eom/posts/l'); 
console.log(response); // undefined
```

- get 함수가 호출되면 XMLHttpRequest 객체를 생성, HTTP 요청을 초기화한 후, HTTP 요청을 전송, xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러를 바인딩하고 종료.

- xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문은 get 함수의 반환문이 아니며, get 함수는 반환문이 생략되었으므로 암묵적으로 undefined를 반환.

- 함수의 반환값은 명시적으로 호출한 다음에 캐치 가능으로 onload 이벤트 핸들러를 get 함수가 호출 가능하다면 이벤트 핸들러의 반환값을 get 함수가 캐치하여 재반환 가능하지만, onload 이벤트 핸들러는 get 함수가 호출하지 않기 때문에 불가능.

- 그렇다면 ①에서 서버의 응답을 상위 스코프의 변수에 할당하면 어떨까?

```js
let todos;
// GET 요청을 위한 비동기 함수 
const get = url => {
  const xhr = new XMLHttpRequest();

  xhr.open('GET', url);

  xhr.send();

  xhr.onload =()=>{
    if (xhr.status === 200) {
      // ① 서버의 응답을 상위 스코프의 변수에 할당한다.
      todos = JSON.parse(xhr.response);
    } else { 
      console.error( ${xhr.status} ${xhr.statusText} ); 
    }
  };
};

// id가 1 인 post를 취득 
get('https://jsonplaceholder.typicode.eom/posts/l'); 
console.log(todos); // undefined
```

- xhr.onload 이벤트 핸들러에서 서버의 응답을 상위 스코프의 변수에 할당(①)하면 처리 순서가 보장되지 않기에 할당 X. WHY?

  - 비동기 함수 get 호출 시 함수 코드를 평가하는 과정에서 get 함수의 실행 컨텍스트가 생성, 실행 컨텍스트 스택에 푸시, 이후 함수 코드 실행 과정에서 xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩.
  
  - get 함수 종료 시 get 함수의 실행 컨텍스트가 콜 스택에서 팝 후 바로 ②의 console.log가 호출, 이때 console.log의 실행 컨텍스트가 생성되어 실행 컨텍스트 스택에 푸시.
  
  - 만약 console.log가 호출되기 직전에 load 이벤트가 발생했더라도 xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러는 결코 console.log보다 먼저 실행 X.
  
  - 서버로부터 응답 도착 시 xhr 객체에서 load 이벤트가 발생, 이때 xhr.onload 핸들러 프로퍼티에 바인딩한 이벤트 핸들러가 즉시 실행 X, load 이벤트 발생 시 태스크 큐에 저장 및 대기 후 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행.
  
  - 이벤트 핸들러도 함수이므로 이벤트 핸들러의 평가 -> 이벤트 핸들러의 실행 컨텍스트 생성 -> 콜 스택에 푸시 -> 이벤트 핸들러 실행 과정 순으로 진행.
  
  - xhr.onload 이벤트 핸들러에서 상위 스코프의 변수에 서버의 응답 결과를 할당하기 이전에 console.log가 먼저 호출되어 undefined가 출력.

- **비동기 함수는 비동기 처리 결과를 외부에 반환 불가능, 상위 스코프의 변수에 할당도 불가능, 따라서 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행 필요.**

- **이때 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이며, 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 비동기 처리가 실패하면 호출될 콜백 함수를 전달 가능.**

```js
// GET 요청을 위한 비동기 함수
const get = (url, successcallback, failureCallback) => {
  const xhr = new XMLHttpRequest();

  xhr.open('GET', url);

  xhr.send();

  xhr.onload =()=>{
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 인수로 전달하면서 호출하여 응답에 대한 후속 처리를 한다. 
      successCallback(JSON.parse(xhr.response));
    } else {
      // 에러 정보를 콜백 함수에 안수로 전달하면서 호출하여 에러 처리를 한다. 
      failureCallback(xhr.status); 
    }
  };
};

// id가 1인 post를 취득
// 서버의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달해야 한다. 
get('https://jsonplaceholder.typicode.eom/posts/l', console.log, console.error); 
/*
  {
    "userid": 1,
    "id": 1,
    "title": "sunt aut facere ... ",
    "body": "quia et suscipit ... "
  }
*/
```

- 콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생.(**콜백 헬**)

```js
// GET 요청을 위한 비동기 함수
const get = (url, callback) => { 
  const xhr = new XMLHttpRequest();

  xhr.open('GET', url);

  xhr.send();

  xhr.onload =()=>{
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 전달하면서 호출하여 응답에 대한 후속 처리를 한다. 
      callback(JSON.parse(xhr.response));
    } else {
      console.error( ${xhr.status} ${xhr.statusText}'); 
    }
  };
};

const url = 'https://jsonplaceholder.typicode.com';

// GET 요청을 위한 비동기 함수
const get = (url, callback) => { 
  const xhr = new XMLHttpRequest();

  xhr.open('GET', url);

  xhr.send();

  xhr.onload =()=>{
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 전달하면서 호출하여 응답에 대한 후속 처리를 한다. 
      callback(JSON.parse(xhr.response));
    } else {
      console.error( ${xhr.status} ${xhr.statusText}'); 
    }
  };
};

const url = 'https://jsonplaceholder.typicode.com';
```

- 위 예제에 GET 요청을 통해 서버로부터 응답을 취득 후 데이터를 사용하여 또다시 GET 요청, 콜백 헬은 가독성을 나쁘게 하며 실수를 유발하는 원인.

```js
get('/stepl', a => {
  get('/step2/${a}', b => {
    get('/step3/${b}', c => {
      get('/step4/${c}', d => {
        console.log(d);
      });
    });
  });
});
```
<br>

###  45.1.2 에러 처리의 한계

- 비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란.

```js
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e);
}
```

<div align="center">
  <img src="https://github.com/user-attachments/assets/c3580dfb-519f-46ac-a44d-5dfbad0c124a">
</div>

- try 코드 블록 내에서 호출한 setTimeout 함수는 1초 후에 콜백 함수가 실행되도록 타이머를 설정 후 콜백 함수는 에러를 발생하지만 이 에러는 catch 코드 블록에서 캐치 X. WHY?

  - 비동기 함수인 setTimeout 호출 시 setTimeout 함수의 실행 컨텍스트가 생성, 콜 스택에 푸시되어 실행하지만 비동기 함수로 콜백 함수가 호출되기 전에 종료되어 콜 스택에서 제거 후 타이머가 만료되면 setTimeout 함수의 콜백 함수는 태스크 큐로 푸시되고 콜 스택이 비어졌을 때 이벤트 루프에 의해 콜 스택으로 푸시되어 실행.
  
  - setTimeout 함수의 콜백 함수가 실행될 때 setTimeout 함수는 이미 콜 스택에서 제거된 상태로 setTimeout 함수의 콜백 함수를 호출한 것이 setTimeout 함수가 아니라는 것을 의미.
  
  - 에러는 호출자 방향으로 전파, 하지만 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니기에 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치 불가능.

- **지금까지 살펴본 비동기 처리를 위한 콜백 패턴은 콜백 헬이나 에러 처리가 곤란하다는 문제가 존재, 이를 극복하기 위해 ES6에서 프로미스가 도입.**
<br>

## 45.2 프로마스의 생성

- Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스를 생성.(ES6에서 도입된 Promise는 호스트 객체가 아닌 ECMAScript 사양에 정의된 표준 빌트인 객체)

- Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인수로 전달.

```js
// 프로미스 생성
const promise = new Promise((resolve, reject) => { 
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다. 
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */ 
    reject('failure reason'); 
  }
});
```

- Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행, 이때 비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 resolve 함수를 호출, 비동기 처리 실패 시 reject 함수를 호출.

- 앞에서 살펴본 비동기 함수 get을 프로미스를 사용해 재구현.

```js
// GET 요청을 위한 비동기 함수
const promiseGet = url => {
  return new Promise((resolve, reject) => { 
    const xhr = new XMLHttpRequest();

    xhr.open('GET', url);

    xhr.send();

    xhr.onload =()=> {
      if (xhr.status === 200) {
        // 성공작으로 응답을 전달받으면 resolve 함수를 호출한다. 
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다. 
        reject(new Error(xhr.status)); 
      } 
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/!');
```

- 비동기 함수인 promiseGet은 함수 내부에서 프로미스를 생성하고 반환, 비동기 처리는 Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 수행.

- 프로미스는 다음과 같이 현재 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보 소유.

<div align="center">
  <img src="https://github.com/user-attachments/assets/0c3fadbb-c777-40ab-8184-1a0f83aafb4a">
</div>

- 생성된 직후의 프로미스는 기본적으로 pending 상태 후 비동기 처리가 수행되면 비동기 처리 결과에 따라 아래와 같이 프로미스의 상태가 변경.

  - **비동기 처리 성공** : resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경.
 
  - **비동기 처리 실패** : reject 함수를 호출해 프로미스를 rejected 상태로 변경.
 
- 이처럼 프로미스의 상태는 resolve or reject 함수를 호출하는 것으로 결정.

<div align="center">
  <img src="https://github.com/user-attachments/assets/ea02dd49-0161-48b5-946f-2784f7b3b98b">
</div>

- fulfilled or rejected 상태를 settled 상태라고 하며, settled 상태는 fulfilled or rejected 상태와 상관없이 pending이 아닌 상태로 비동기 처리가 수행된 상태.

- 프로미스는 pending 상태에서 settled 상태로 변화 가능하며, 일단 settled 상태가 되면 더는 다른 상태로 변화 불가능, 비동기 처리 상태와 더불어 비동기 처리 결과 가짐.

- 아래의 프로미스를 개발자 도구에서 출력 시.

```
// fulfilled된 프로미스
const fulfilled = new Promise(resolve => resolve(l));
```

<div align="center">
  <img src="https://github.com/user-attachments/assets/25ce02cb-1551-491f-aed7-d0a75056f345">
</div>

- 비동기 처리 성공 시 프로미스는 pending 상태에서 fulfilled 상태로 변화, 비동기 처리 결과는 1.

```
 // rejected된 프로미스
const rejected = new Promise((_, reject) => reject(new Error('error occurred')));
```

<div align="center">
  <img src="https://github.com/user-attachments/assets/c1564263-488b-47ac-9bd2-7914e84336d5">
</div>

- 비동기 처리가 실패하면 프로미스는 pending 상태에서 rejected 상태로 변화, 비동기 처리 결과는 Error 객체.

- **프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체.**
<br>

## 45.3 프로미스의 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리 필요. (프로미스는 후속 메서드 then, catch, finally를 제공)

- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출되고 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달.

- 모든 후속 처리 메서드는 프로미스를 반환하며, 비동기로 동작.
<br>

### 45.3.1 Promise.prototype.then

- then 메서드는 두 개의 콜백 함수를 인수로 전달.

  - 첫 번째 콜백 함수는 프로미스가 fulfilled 상태가 되면 호출, 이때 활백 함수는 프로미스의 비동기 처리 결과를 인수로 전달.
 
  - 두 번째 콜백 함수는 프로미스가 rejected 상태가 되면 호출, 이때 콜백 함수는 프로마스의 에러를 인수로 전달.

```
// fulfilled
new Promise(resolve => resolve( fulfilled'))
  .then(v => console.log(v), e => console.error(e)); // fulfilled

// rejected
new Promise((_r reject) => reject(new Error('rejected1)))
  .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

- then 메서드는 언제나 프로미스를 반환, 만약 then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve or reject하여 프로미스를 생성해 반환.
<br>

### 45.3.2 Promise.prototype.catch

- catch 메서드는 한 개의 콜백 함수를 인수로 전달, catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출.

```
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .catch(e => console.log(e)); // Error: rejected
```

- catch 메서드는 then(undefined, onRejected)과 동일하게 동작한다. 따라서 then 메서드와 마찬가지로 언제나 프로미스를 반환.

```
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(undefined, e => console.log(e)); // Error: rejected
```
<br>

### 45.3.3 Promise.prototype.finally

- finally 메서드는 한 개의 콜백 함수를 인수로 전달, finally 메서드의 콜백 함수는 프로미스의 성공 or 실패와 상관없이 무조건 한 번 호출.

- finally 메서드는 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용.

```
new Promise(() => {})
 .finally(() => console.log('finally')); // finally
```

- 프로미스로 구현한 비동기 함수 get을 사용해 후속 처리를 구현 시.

```js
const promiseGet = url => {
  return new Promise((resolve, reject) => { 
    const xhr = new XMLHttpRequest();

    xhr.open('GET', url);

    xhr.send();

    xhr.onload =()=>{

      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다. 
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다. 
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/l,)
.then(res => console.log(res))
.catch(err => console.error(err))
.finally(() => console.log( 'Bye!'));
```
<br>

## 45.4 프로미스의 에러 처리

- 45.1.2절 "에러 처리의 한계"에서 살펴보았듯 비동기 처리를 위한 콜백 패턴은 에러 처리가 곤란하다는 문제가 존재, 프로미스는 에러를 문제없이 처리 가능.

- 위 예제의 비동기 함수 get은 프로미스를 반환, 비동기 처리 결과에 대한 후속 처리는 프로미스가 제공하는 후속 처리 메서드 then, catch, finally를 사용하여 수행.

- 비동기 처리에서 발생한 에러는 then 메서드의 두 번째 콜백 함수로 처리 가능.

```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 자정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl).then(
  res => console.log(res),
  err => console.error(err)
); // Error: 404
```

- 비동기 처리에서 발생한 에러는 프로미스의 후속 처리 메서드 catch를 사용해 처리 가능.

```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 자정되었기 때문에 에러가 일생한다.
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(err => console.error(err)); // Error： 404
```

- catch 메서드 호출 시 내부적으로 then을 호출하기에 위 예제는 내부적으로 다음과 같이 처리.

```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .then(undefined, err => console.error(err)); // Error: 404
```

- 단, then 메서드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고 코드가 복잡해져서 가독성 저해.

```js
promiseGet('https://jsonplaceholder.typicode.eom/todos/l').then(
  res => console.xxx(res),
  err => console.error(err)
); // 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치 불가능.
```

- catch 메서드를 모든 then 메서드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러뿐 아니라 then 메서드 내부에서 발생한 에러까지 모두 캐치 가능.

```js
promiseGet('https://jsonplaceholder.typicode.eom/todos/l')
  .then(res => console.xxx(res))
  .catch(err => console.error(err)); // Type Error: console.xxx is not a function
```

- 또한 then 메서드에 두 번째 콜백 함수를 전달하는 것보다 catch 메서드를 사용하는 것이 가독성 향상에 도움이 되기에 에러 처리는 then 메서드에서 하지 말고 catch 메서드에서 하는 것을 권장.
<br>
















